import { m140ResolveOutcomes } from './m140-resolve-outcomes';
import { m141AttributionFooter } from './m141-attribution-footer';
import { m142ResolvePublications } from './m142-resolve-publications';
import { m143DropPendingResolutions } from './m143-drop-pending-resolutions';
import { m144SessionMountLifecycle } from './m144-session-mount-lifecycle';
import { m145SessionEventPrDiscovered } from './m145-session-event-pr-discovered';
import { m146PrSeries } from './m146-pr-series';
import { m001Initial } from './m001-initial';
import { m002TelemetryKind } from './m002-telemetry-kind';
import { m003SessionProvider } from './m003-session-provider';
import { m004TurnOverrides } from './m004-turn-overrides';
import { m005BudgetTables } from './m005-budget-tables';
import { m006Skills } from './m006-skills';
import { m007Phases } from './m007-phases';
import { m008Permissions } from './m008-permissions';
import { m009SessionWorktrees } from './m009-session-worktrees';
import { m010PermissionAuditRetry } from './m010-permission-audit-retry';
import { m011ParallelPhases } from './m011-parallel-phases';
import { m012SettingsOverrides } from './m012-settings-overrides';
import { m013BudgetExtraTokens } from './m013-budget-extra-tokens';
import { m014RenameDomain } from './m014-rename-domain';
import { m015AgentsPerChat } from './m015-agents-per-chat';
import { m016TurnEvents } from './m016-turn-events';
import { m017ContextSlotHistory } from './m017-context-slot-history';
import { m018GithubPrCache } from './m018-github-pr-cache';
import { m019TaskPermissionMode } from './m019-task-permission-mode';
import { m020DiffComments } from './m020-diff-comments';
import { m021DiffCommentLine } from './m021-diff-comment-line';
import { m022TaskAutorun } from './m022-task-autorun';
import { m023StepEffort } from './m023-step-effort';
import { m024SessionProviderSessionId } from './m024-session-provider-session-id';
import { m025TaskTitleUserEdited } from './m025-task-title-user-edited';
import { m026Notifications } from './m026-notifications';
import { m027SessionPlans } from './m027-session-plans';
import { m028DiffCommentConsumed } from './m028-diff-comment-consumed';
import { m029AgentUnread } from './m029-agent-unread';
import { m030PlanConsumptions } from './m030-plan-consumptions';
import { m031RenameSoftDeletePersist } from './m031-rename-soft-delete-persist';
import { m032SessionUserStatus } from './m032-session-user-status';
import { m033WorkspaceInitScripts } from './m033-workspace-init-scripts';
import { m034WorkspaceDisconnectedAt } from './m034-workspace-disconnected-at';
import { m035NudgeEvents } from './m035-nudge-events';
import { m036WorkspaceScripts } from './m036-workspace-scripts';
import { m037PlanDiscardedStatus } from './m037-plan-discarded-status';
import { m038WorkspaceVerbosity } from './m038-workspace-verbosity';
import { m039WorkspaceLastAccessedAt } from './m039-workspace-last-accessed-at';
import { m040OpenQuestions } from './m040-open-questions';
import { m041SessionWorkflows } from './m041-session-workflows';
import { m042OpenQuestionsCreatedBy } from './m042-open-questions-created-by';
import { m043WorkspaceIntegrations } from './m043-workspace-integrations';
import { m044SessionExternalTask } from './m044-session-external-task';
import { m045StepLibrary } from './m045-step-library';
import { m046StepRole } from './m046-step-role';
import { m047AgentParent } from './m047-agent-parent';
import { m048PlanClusters } from './m048-plan-clusters';
import { m049SessionWorkflowDiscard } from './m049-session-workflow-discard';
import { m050ProviderCredentials } from './m050-provider-credentials';
import { m051ProviderBindings } from './m051-provider-bindings';
import { m052PendingResolutions } from './m052-pending-resolutions';
import { m053ScoutFanout } from './m053-scout-fanout';
import { m054WorkflowRunInstances } from './m054-workflow-run-instances';
import { m055ResolverCommentLink } from './m055-resolver-comment-link';
import { m056CompositeWorkspaces } from './m056-composite-workspaces';
import { m057SessionEnabledProviders } from './m057-session-enabled-providers';
import { m058WorkflowGoal } from './m058-workflow-goal';
import { m059WorkflowRunGoal } from './m059-workflow-run-goal';
import { m060WorkflowTriggerMode } from './m060-workflow-trigger-mode';
import { m061DiffCommentLineRange } from './m061-diff-comment-line-range';
import { m062OpenQuestionsTurnOrdinal } from './m062-open-questions-turn-ordinal';
import { m063OpenQuestionsRecommendedAnswer } from './m063-open-questions-recommended-answer';
import { m064SentryProvider } from './m064-sentry-provider';
import { m065IntegrationGitlabProvider } from './m065-integration-gitlab-provider';
import { m066GoalAttachments } from './m066-goal-attachments';
import { m067GeminiProviderRun } from './m067-gemini-provider-run';
import { m068ProviderRunsGeminiRepair } from './m068-provider-runs-gemini-repair';
import { m069RefactorExampleOnly } from './m069-refactor-example-only';
import { m070StepLibraryExampleOnly } from './m070-step-library-example-only';
import { m071SessionExternalTaskMultipleLinks } from './m071-session-external-task-multiple-links';
import { m072TaskModels } from './m072-task-models';
import { m073SessionExternalTaskGithubProvider } from './m073-session-external-task-github-provider';
import { m074NotificationAction } from './m074-notification-action';
import { m075PrReviewDrafts } from './m075-pr-review-drafts';
import { m076AgentSourceKind } from './m076-agent-source-kind';
import { m077StepExpectedOutput } from './m077-step-expected-output';
import { m078WorkflowProcessText } from './m078-workflow-process-text';
import { m079RoleModels } from './m079-role-models';
import { m080AgentDone } from './m080-agent-done';
import { m081RoleCleanup } from './m081-role-cleanup';
import { m082AgentSourceThreads } from './m082-agent-source-threads';
import { m083AgentDomains } from './m083-agent-domains';
import { m084WorkspaceProviderPool } from './m084-workspace-provider-pool';
import { m085OpencodeOpenrouterProviderRuns } from './m085-opencode-openrouter-provider-runs';
import { m086ImpactIndexes } from './m086-impact-indexes';
import { m087AgentProviderSessionProvider } from './m087-agent-provider-session-provider';
import { m088PendingResolutionReply } from './m088-pending-resolution-reply';
import { m089TelemetryCacheTokens } from './m089-telemetry-cache-tokens';
import { m090TelemetryContextTokens } from './m090-telemetry-context-tokens';
import { m091WorkflowExecutionMode } from './m091-workflow-execution-mode';
import { m092WorkflowNameUniqueLive } from './m092-workflow-name-unique-live';
import { m093StepOrchestratorReason } from './m093-step-orchestrator-reason';
import { m094WorkflowOrchestrationState } from './m094-workflow-orchestration-state';
import { m095WorkflowOrchestratorRouting } from './m095-workflow-orchestrator-routing';
import { m096SessionExternalTaskMount } from './m096-session-external-task-mount';
import { m097SessionActiveMount } from './m097-session-active-mount';
import { m098WorkflowStepRouting } from './m098-workflow-step-routing';
import { m099FileVersions } from './m099-file-versions';
import { m100WorkflowOrigin } from './m100-workflow-origin';
import { m101TelemetryOrchestratorKind } from './m101-telemetry-orchestrator-kind';
import { m102WorkflowOrchestrationStopKind } from './m102-workflow-orchestration-stop-kind';
import { m103SessionExternalTaskBranch } from './m103-session-external-task-branch';
import { m104PendingResolutionReplyPosted } from './m104-pending-resolution-reply-posted';
import { m105IntegrationJiraProvider } from './m105-integration-jira-provider';
import { m106MoonshotProviderRuns } from './m106-moonshot-provider-runs';
import { m107IntegrationBitbucketProvider } from './m107-integration-bitbucket-provider';
import { m108IntegrationSlackProvider } from './m108-integration-slack-provider';
import { m109WorkflowRunSummary } from './m109-workflow-run-summary';
import { m110WorkflowRunSpendLimit } from './m110-workflow-run-spend-limit';
import { m111SessionWorktreeRepoSlug } from './m111-session-worktree-repo-slug';
import { m112OpenQuestionsSelectMode } from './m112-open-questions-select-mode';
import { m113WorkflowRunRoleModels } from './m113-workflow-run-role-models';
import { m114IntegrationCredentials } from './m114-integration-credentials';
import { m115SessionEvents } from './m115-session-events';
import { m116SessionEventWorkflowRestored } from './m116-session-event-workflow-restored';
import { m117RenameProjects } from './m117-rename-projects';
import { m118WorkspaceContainers } from './m118-workspace-containers';
import { m119ProjectSessionRelations } from './m119-project-session-relations';
import { m120WorkspaceProfiles } from './m120-workspace-profiles';
import { m121ProjectSessionMounts } from './m121-project-session-mounts';
import { m122RuntimeDeadWeight } from './m122-runtime-dead-weight';
import { m123StorageCleanup } from './m123-storage-cleanup';
import { m124TombstoneGc } from './m124-tombstone-gc';
import { m125NormalizeTimestamps } from './m125-normalize-timestamps';
import { m126UnconstrainProviderColumns } from './m126-unconstrain-provider-columns';
import { m127AddWorkflowReferenceForeignKeys } from './m127-add-workflow-reference-foreign-keys';
import { m128NormalizeGoalAttachmentOwners } from './m128-normalize-goal-attachment-owners';
import { m129ImpactQueryIndexes } from './m129-impact-query-indexes';
import { m130SessionEventLazyProjects } from './m130-session-event-lazy-projects';
import { m131IntegrationBindings } from './m131-integration-bindings';
import { m132WorkspaceProfileBio } from './m132-workspace-profile-bio';
import { m133SessionEventProjectDetached } from './m133-session-event-project-detached';
import { m134SessionActiveProjects } from './m134-session-active-projects';
import { m135SupersedeDiscardedWorkflowPlans } from './m135-supersede-discarded-workflow-plans';
import { m136ProjectBaseBranch } from './m136-project-base-branch';
import { m137NotificationCoalesceKey } from './m137-notification-coalesce-key';
import { m138SessionEventMaterializationProposals } from './m138-session-event-materialization-proposals';
import { m139SessionEventRebaseRequested } from './m139-session-event-rebase-requested';

export type Migration = {
  readonly version: number;
  readonly sql: string;
};

export const migrations: ReadonlyArray<Migration> = [
  { version: 1, sql: m001Initial },
  { version: 2, sql: m002TelemetryKind },
  { version: 3, sql: m003SessionProvider },
  { version: 4, sql: m004TurnOverrides },
  { version: 5, sql: m005BudgetTables },
  { version: 6, sql: m006Skills },
  { version: 7, sql: m007Phases },
  { version: 8, sql: m008Permissions },
  { version: 9, sql: m009SessionWorktrees },
  { version: 10, sql: m010PermissionAuditRetry },
  { version: 11, sql: m011ParallelPhases },
  { version: 12, sql: m012SettingsOverrides },
  { version: 13, sql: m013BudgetExtraTokens },
  { version: 14, sql: m014RenameDomain },
  { version: 15, sql: m015AgentsPerChat },
  { version: 16, sql: m016TurnEvents },
  { version: 17, sql: m017ContextSlotHistory },
  { version: 18, sql: m018GithubPrCache },
  { version: 19, sql: m019TaskPermissionMode },
  { version: 20, sql: m020DiffComments },
  { version: 21, sql: m021DiffCommentLine },
  { version: 22, sql: m022TaskAutorun },
  { version: 23, sql: m023StepEffort },
  { version: 24, sql: m024SessionProviderSessionId },
  { version: 25, sql: m025TaskTitleUserEdited },
  { version: 26, sql: m026Notifications },
  { version: 27, sql: m027SessionPlans },
  { version: 28, sql: m028DiffCommentConsumed },
  { version: 29, sql: m029AgentUnread },
  { version: 30, sql: m030PlanConsumptions },
  { version: 31, sql: m031RenameSoftDeletePersist },
  { version: 32, sql: m032SessionUserStatus },
  { version: 33, sql: m033WorkspaceInitScripts },
  { version: 34, sql: m034WorkspaceDisconnectedAt },
  { version: 35, sql: m035NudgeEvents },
  { version: 36, sql: m036WorkspaceScripts },
  { version: 37, sql: m037PlanDiscardedStatus },
  { version: 38, sql: m038WorkspaceVerbosity },
  { version: 39, sql: m039WorkspaceLastAccessedAt },
  { version: 40, sql: m040OpenQuestions },
  { version: 41, sql: m041SessionWorkflows },
  { version: 42, sql: m042OpenQuestionsCreatedBy },
  { version: 43, sql: m043WorkspaceIntegrations },
  { version: 44, sql: m044SessionExternalTask },
  { version: 45, sql: m045StepLibrary },
  { version: 46, sql: m046StepRole },
  { version: 47, sql: m047AgentParent },
  { version: 48, sql: m048PlanClusters },
  { version: 49, sql: m049SessionWorkflowDiscard },
  { version: 50, sql: m050ProviderCredentials },
  { version: 51, sql: m051ProviderBindings },
  { version: 52, sql: m052PendingResolutions },
  { version: 53, sql: m053ScoutFanout },
  { version: 54, sql: m054WorkflowRunInstances },
  { version: 55, sql: m055ResolverCommentLink },
  { version: 56, sql: m056CompositeWorkspaces },
  { version: 57, sql: m057SessionEnabledProviders },
  { version: 58, sql: m058WorkflowGoal },
  { version: 59, sql: m059WorkflowRunGoal },
  { version: 60, sql: m060WorkflowTriggerMode },
  { version: 61, sql: m061DiffCommentLineRange },
  { version: 62, sql: m062OpenQuestionsTurnOrdinal },
  { version: 63, sql: m063OpenQuestionsRecommendedAnswer },
  { version: 64, sql: m064SentryProvider },
  { version: 65, sql: m065IntegrationGitlabProvider },
  { version: 66, sql: m066GoalAttachments },
  { version: 67, sql: m067GeminiProviderRun },
  { version: 68, sql: m068ProviderRunsGeminiRepair },
  { version: 69, sql: m069RefactorExampleOnly },
  { version: 70, sql: m070StepLibraryExampleOnly },
  { version: 71, sql: m071SessionExternalTaskMultipleLinks },
  { version: 72, sql: m072TaskModels },
  { version: 73, sql: m073SessionExternalTaskGithubProvider },
  { version: 74, sql: m074NotificationAction },
  { version: 75, sql: m075PrReviewDrafts },
  { version: 76, sql: m076AgentSourceKind },
  { version: 77, sql: m077StepExpectedOutput },
  { version: 78, sql: m078WorkflowProcessText },
  { version: 79, sql: m079RoleModels },
  { version: 80, sql: m080AgentDone },
  { version: 81, sql: m081RoleCleanup },
  { version: 82, sql: m082AgentSourceThreads },
  { version: 83, sql: m083AgentDomains },
  { version: 84, sql: m084WorkspaceProviderPool },
  { version: 85, sql: m085OpencodeOpenrouterProviderRuns },
  { version: 86, sql: m086ImpactIndexes },
  { version: 87, sql: m087AgentProviderSessionProvider },
  { version: 88, sql: m088PendingResolutionReply },
  { version: 89, sql: m089TelemetryCacheTokens },
  { version: 90, sql: m090TelemetryContextTokens },
  { version: 91, sql: m091WorkflowExecutionMode },
  { version: 92, sql: m092WorkflowNameUniqueLive },
  { version: 93, sql: m093StepOrchestratorReason },
  { version: 94, sql: m094WorkflowOrchestrationState },
  { version: 95, sql: m095WorkflowOrchestratorRouting },
  { version: 96, sql: m096SessionExternalTaskMount },
  { version: 97, sql: m097SessionActiveMount },
  { version: 98, sql: m098WorkflowStepRouting },
  { version: 99, sql: m099FileVersions },
  { version: 100, sql: m100WorkflowOrigin },
  { version: 101, sql: m101TelemetryOrchestratorKind },
  { version: 102, sql: m102WorkflowOrchestrationStopKind },
  { version: 103, sql: m103SessionExternalTaskBranch },
  { version: 104, sql: m104PendingResolutionReplyPosted },
  { version: 105, sql: m105IntegrationJiraProvider },
  { version: 106, sql: m106MoonshotProviderRuns },
  { version: 107, sql: m107IntegrationBitbucketProvider },
  { version: 108, sql: m108IntegrationSlackProvider },
  { version: 109, sql: m109WorkflowRunSummary },
  { version: 110, sql: m110WorkflowRunSpendLimit },
  { version: 111, sql: m111SessionWorktreeRepoSlug },
  { version: 112, sql: m112OpenQuestionsSelectMode },
  { version: 113, sql: m113WorkflowRunRoleModels },
  { version: 114, sql: m114IntegrationCredentials },
  { version: 115, sql: m115SessionEvents },
  { version: 116, sql: m116SessionEventWorkflowRestored },
  { version: 117, sql: m117RenameProjects },
  { version: 118, sql: m118WorkspaceContainers },
  { version: 119, sql: m119ProjectSessionRelations },
  { version: 120, sql: m120WorkspaceProfiles },
  { version: 121, sql: m121ProjectSessionMounts },
  { version: 122, sql: m122RuntimeDeadWeight },
  { version: 123, sql: m123StorageCleanup },
  { version: 124, sql: m124TombstoneGc },
  { version: 125, sql: m125NormalizeTimestamps },
  { version: 126, sql: m126UnconstrainProviderColumns },
  { version: 127, sql: m127AddWorkflowReferenceForeignKeys },
  { version: 128, sql: m128NormalizeGoalAttachmentOwners },
  { version: 129, sql: m129ImpactQueryIndexes },
  { version: 130, sql: m130SessionEventLazyProjects },
  { version: 131, sql: m131IntegrationBindings },
  { version: 132, sql: m132WorkspaceProfileBio },
  { version: 133, sql: m133SessionEventProjectDetached },
  { version: 134, sql: m134SessionActiveProjects },
  { version: 135, sql: m135SupersedeDiscardedWorkflowPlans },
  { version: 136, sql: m136ProjectBaseBranch },
  { version: 137, sql: m137NotificationCoalesceKey },
  { version: 138, sql: m138SessionEventMaterializationProposals },
  { version: 139, sql: m139SessionEventRebaseRequested },
  { version: 140, sql: m140ResolveOutcomes },
  { version: 141, sql: m141AttributionFooter },
  { version: 142, sql: m142ResolvePublications },
  { version: 143, sql: m143DropPendingResolutions },
  { version: 144, sql: m144SessionMountLifecycle },
  { version: 145, sql: m145SessionEventPrDiscovered },
  { version: 146, sql: m146PrSeries },
];
