export type { DetailEntry, DetailFieldRegistry } from './types';
export { resolveDetailFields, type ResolvedDetailFields } from './resolveDetailFields';
export { linearIssueFields } from './linearIssueFields';
export { sentryIssueFields, type SentryIssueProperties } from './sentryIssueFields';
export { githubIssueFields } from './githubIssueFields';
export { githubPullRequestFields } from './githubPullRequestFields';
export { gitlabIssueFields } from './gitlabIssueFields';
export { gitlabMergeRequestFields } from './gitlabMergeRequestFields';
export { bitbucketPullRequestFields } from './bitbucketPullRequestFields';
export { jiraIssueFields } from './jiraIssueFields';
export { slackThreadFields, type SlackThreadProperties } from './slackThreadFields';
