import type { AppState } from './types';

export type EvictionScope = 'session' | 'agent' | 'workflowRun';
export type EvictionMode = 'archive' | 'delete';

export type SessionEvictionRule = {
  readonly key: keyof AppState;
  readonly keyedBy: EvictionScope;
  readonly evictOn: EvictionMode;
};

export const SESSION_EVICTION = [
  { key: 'sessionResolveThreads', keyedBy: 'session', evictOn: 'archive' },
  { key: 'sessionResolveAttempts', keyedBy: 'session', evictOn: 'archive' },
  { key: 'sessionWorktrees', keyedBy: 'session', evictOn: 'archive' },
  { key: 'sessionWorktreeRecords', keyedBy: 'session', evictOn: 'archive' },
  { key: 'sessionProjectMounts', keyedBy: 'session', evictOn: 'archive' },
  { key: 'sessionMounts', keyedBy: 'session', evictOn: 'archive' },
  { key: 'mountBranchObservations', keyedBy: 'session', evictOn: 'archive' },
  { key: 'sessionActiveMount', keyedBy: 'session', evictOn: 'archive' },
  { key: 'sessionLanguageAnchor', keyedBy: 'session', evictOn: 'archive' },
  { key: 'sessionActiveProject', keyedBy: 'session', evictOn: 'archive' },
  { key: 'sessionBranches', keyedBy: 'session', evictOn: 'archive' },
  { key: 'sessionPhaseRuns', keyedBy: 'session', evictOn: 'archive' },
  { key: 'sessionGithub', keyedBy: 'session', evictOn: 'archive' },
  { key: 'sessionProjectPrs', keyedBy: 'session', evictOn: 'archive' },
  { key: 'sessionSelectedPrNumber', keyedBy: 'session', evictOn: 'archive' },
  { key: 'sessionLoading', keyedBy: 'session', evictOn: 'archive' },
  { key: 'selectedAgentId', keyedBy: 'session', evictOn: 'archive' },
  { key: 'sessionOpenQuestions', keyedBy: 'session', evictOn: 'archive' },
  { key: 'sessionWorkflows', keyedBy: 'session', evictOn: 'archive' },
  { key: 'sessionTelemetry', keyedBy: 'session', evictOn: 'archive' },
  { key: 'sessionSlots', keyedBy: 'session', evictOn: 'archive' },
  { key: 'slotHistory', keyedBy: 'session', evictOn: 'archive' },
  { key: 'slotHistoryCounts', keyedBy: 'session', evictOn: 'archive' },
  { key: 'sessionSlotsLoad', keyedBy: 'session', evictOn: 'archive' },
  { key: 'summarizerStatus', keyedBy: 'session', evictOn: 'archive' },
  { key: 'sessionGitlabMr', keyedBy: 'session', evictOn: 'archive' },
  { key: 'sessionBitbucketPr', keyedBy: 'session', evictOn: 'archive' },
  { key: 'sessionBitbucketRepo', keyedBy: 'session', evictOn: 'archive' },
  { key: 'sessionSelectedBitbucketPrId', keyedBy: 'session', evictOn: 'archive' },
  { key: 'reviewDrafts', keyedBy: 'session', evictOn: 'archive' },
  { key: 'sessionPendingResolutions', keyedBy: 'session', evictOn: 'archive' },
  { key: 'sessionResolvedThreads', keyedBy: 'session', evictOn: 'archive' },
  { key: 'sessionPlans', keyedBy: 'session', evictOn: 'archive' },
  { key: 'sessionAnsweredQuestions', keyedBy: 'session', evictOn: 'archive' },
  { key: 'sessionDismissedQuestions', keyedBy: 'session', evictOn: 'archive' },
  { key: 'sessionNudges', keyedBy: 'session', evictOn: 'archive' },
  { key: 'sessionAttachments', keyedBy: 'session', evictOn: 'archive' },
  { key: 'sessionOverrides', keyedBy: 'session', evictOn: 'archive' },
  { key: 'scriptRuns', keyedBy: 'session', evictOn: 'archive' },
  { key: 'discoveredScripts', keyedBy: 'session', evictOn: 'archive' },
  { key: 'discoveredScriptScans', keyedBy: 'session', evictOn: 'archive' },
  { key: 'sessionPanelExpanded', keyedBy: 'session', evictOn: 'archive' },
  { key: 'activeLens', keyedBy: 'session', evictOn: 'archive' },
  { key: 'lensHistory', keyedBy: 'session', evictOn: 'archive' },
  { key: 'workflowExpand', keyedBy: 'session', evictOn: 'archive' },
  { key: 'focusedWorkflowRunId', keyedBy: 'session', evictOn: 'archive' },
  { key: 'diffFocus', keyedBy: 'session', evictOn: 'archive' },
  { key: 'diffMountPath', keyedBy: 'session', evictOn: 'archive' },
  { key: 'sessionCreations', keyedBy: 'session', evictOn: 'archive' },
  { key: 'sessionStudio', keyedBy: 'session', evictOn: 'archive' },
  { key: 'focusedPlanId', keyedBy: 'session', evictOn: 'archive' },
  { key: 'focusedGithubIssueNumber', keyedBy: 'session', evictOn: 'archive' },
  { key: 'focusedExternalTask', keyedBy: 'session', evictOn: 'archive' },
  { key: 'diffComments', keyedBy: 'session', evictOn: 'archive' },
  { key: 'transcripts', keyedBy: 'agent', evictOn: 'archive' },
  { key: 'messages', keyedBy: 'agent', evictOn: 'archive' },
  { key: 'agentDraft', keyedBy: 'agent', evictOn: 'archive' },
  { key: 'agentAttachments', keyedBy: 'agent', evictOn: 'archive' },
  { key: 'agentQueue', keyedBy: 'agent', evictOn: 'archive' },
  { key: 'sessionExternalTasks', keyedBy: 'session', evictOn: 'delete' },
  { key: 'sessionEvents', keyedBy: 'session', evictOn: 'delete' },
  { key: 'workflowDrafts', keyedBy: 'session', evictOn: 'delete' },
  { key: 'sessionFileVersions', keyedBy: 'session', evictOn: 'delete' },
  { key: 'sessionFileVersionsLoading', keyedBy: 'session', evictOn: 'delete' },
  { key: 'sessionFileVersionSelectedPath', keyedBy: 'session', evictOn: 'delete' },
  { key: 'sessionBudgets', keyedBy: 'session', evictOn: 'delete' },
  { key: 'terminalSessions', keyedBy: 'session', evictOn: 'delete' },
  { key: 'terminalTabs', keyedBy: 'session', evictOn: 'delete' },
  { key: 'activeTerminalTab', keyedBy: 'session', evictOn: 'delete' },
  { key: 'pendingAdvanceSessions', keyedBy: 'session', evictOn: 'delete' },
  { key: 'agentRunHistory', keyedBy: 'agent', evictOn: 'delete' },
  { key: 'agentTurnState', keyedBy: 'agent', evictOn: 'delete' },
  { key: 'clusterStartAttempts', keyedBy: 'agent', evictOn: 'delete' },
  { key: 'agentModelOverride', keyedBy: 'agent', evictOn: 'delete' },
  { key: 'agentProviderOverride', keyedBy: 'agent', evictOn: 'delete' },
  { key: 'agentEffortOverride', keyedBy: 'agent', evictOn: 'delete' },
  { key: 'agentKindOverride', keyedBy: 'agent', evictOn: 'delete' },
  { key: 'resolverState', keyedBy: 'agent', evictOn: 'delete' },
  { key: 'resolverThreadOutcomes', keyedBy: 'agent', evictOn: 'delete' },
  { key: 'workflowRunAttachments', keyedBy: 'workflowRun', evictOn: 'delete' },
  { key: 'orchestratingWorkflowRuns', keyedBy: 'workflowRun', evictOn: 'delete' },
  { key: 'announcedWorkflowBlocks', keyedBy: 'workflowRun', evictOn: 'delete' },
  { key: 'announcedRunBudget', keyedBy: 'workflowRun', evictOn: 'delete' },
  { key: 'pendingOrchestrations', keyedBy: 'workflowRun', evictOn: 'delete' },
] as const satisfies ReadonlyArray<SessionEvictionRule>;

export const NON_SESSION_STATE_KEYS = [
  'selectedProjectIds',
  'workspaces',
  'projects',
  'workspaceIntegrations',
  'integrationCredentials',
  'integrationCredentialUsage',
  'projectGitStatus',
  'projectCheckoutPulling',
  'currentWorkspaceId',
  'windowPresence',
  'sessions',
  'archivedSessions',
  'currentSessionId',
  'pendingTitleFocusSessionId',
  'settings',
  'sessionSummary',
  'providerStatus',
  'cursorStatus',
  'codexStatus',
  'geminiStatus',
  'authResults',
  'providers',
  'providerLifecycle',
  'providerConnect',
  'providerCredentials',
  'providerCooldowns',
  'hydrated',
  'bootPhase',
  'error',
  'orphanWorktrees',
  'workspaceSummary',
  'storageStats',
  'storageStatsLoading',
  'budgetRules',
  'providerSpendBreakdown',
  'budgetAlerts',
  'skills',
  'projectScripts',
  'phaseTemplates',
  'stepLibrary',
  'unknownPayloadCounts',
  'detectedEditors',
  'workspaceOverrides',
  'unreadWorkspaceIds',
  'githubStatus',
  'reviewPrs',
  'volatilePermissionAllows',
  'workflowStudioDrafts',
  'workflowGenerations',
  'visibleWorkflowStudioWorkspaceId',
  'notifications',
  'notificationsLoading',
  'notificationCounts',
  'planConsumptions',
  'openQuestionScrollTarget',
  'boardReady',
  'scriptsLensScope',
  'reviewLensIntent',
  'sessionViewPrefs',
  'updaterStatus',
  'updateVersion',
  'updateError',
  'changelogReleases',
  'changelogStatus',
  'changelogError',
  'changelogFetchedAt',
  'changelogSeenVersion',
  'bugReportDraft',
  'slackChannels',
  'slackUsers',
  'slackThreadHeads',
  'slackThreads',
] as const satisfies ReadonlyArray<keyof AppState>;

type RegisteredKey =
  (typeof SESSION_EVICTION)[number]['key'] | (typeof NON_SESSION_STATE_KEYS)[number];
type UnregisteredKey = Exclude<keyof AppState, RegisteredKey>;

const allStateKeysClassified: UnregisteredKey extends never ? true : UnregisteredKey = true;
