export const RESOLVER_KICKOFF_LABELS = {
  headline: /^Resolve \d+ threads? on PR #\d+/,
  threadHeader: /^Thread (\d+) of (\d+)$/,
  threadId: '- thread id: ',
  author: '- author: ',
  location: '- location: ',
  link: '- link: ',
  comment: '- comment:',
  replyFrom: /^- reply from (.+):$/,
  quote: '>',
  instructions: 'What to do',
  reporting: 'How to report each thread',
  replyContract: 'Reply contract',
  priorWork: 'What already happened',
  operatorNotes: 'Operator notes',
} as const;
