import {
  ArrowRight,
  CheckCheck,
  CircleStop,
  Clock,
  Hammer,
  HelpCircle,
  ListChecks,
  MessageSquareReply,
  PenLine,
  Play,
  RefreshCw,
  RotateCcw,
  RotateCw,
  Upload,
  X,
  type LucideIcon,
} from 'lucide-react';
import type { ResolverActionKind } from './resolverActions';

export const RESOLVER_ACTION_ICON: Record<ResolverActionKind, LucideIcon> = {
  push: Upload,
  queue: Clock,
  dequeue: X,
  explain: MessageSquareReply,
  proceed: Play,
  answer: ArrowRight,
  review: ListChecks,
  rerun: RotateCcw,
  fix: Hammer,
  rework: RefreshCw,
  redo: RotateCw,
  custom: PenLine,
  verdict: HelpCircle,
  forceClose: CircleStop,
  forceResolve: CheckCheck,
};
